n<-as.integer(readline(prompt="enter the number of students"))
USN<-vector(mode="character",length=n)
Name<-vector(mode="character",length=n)
Marks<-vector(mode="numeric",length=n)
print("enter USN")
for(i in 1:n)
  USN[i]<-as.character(readline())
print("enter Name")
for(i in 1:n)
  Name[i]<-as.character(readline())
print("enter Marks")
for(i in 1:n)
  Marks[i]<-as.numeric(readline())
student<-data.frame(USN,Name,Marks)
print("student details")
print(student)
print("age")
age<-vector(mode="integer",length=n)
for(i in 1:n)
  age[i]<-as.integer(readline())
student<-cbind(student,age)
print(student)
for(i in 1:n)
  if(student[i,3]>25)
    if(student[i,4]<20)
      print(student[i,])
